name: Lint, Test & Deploy (1 job)
on: push
jobs:
   all-in-one:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test code
              run: npm run test
            - name: Build code
              run: npm run build
            - name: Deploy code
              run: echo "Deploying..."