name: Lint, Test & Deploy
on: push
jobs:
   all-in-one:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Lint
              uses: super-linter/super-linter@v6.3.0
            - name: Test
              run: echo "Test"
            - name: Build
              run: echo "Build"   
